// Curated meme templates for the $BEEF roast bot.
//
// Tier 1: rich annotations — 20 templates with structure, 3 crypto examples, antiPatterns.
// Tier 2: basic annotations — 20+ templates with structure, 1 example.
//
// Source: Imgflip top-100 (https://api.imgflip.com/get_memes), filtered for box_count <= 3,
// annotated for crypto roast context.

export interface MemeTemplate {
  id: string;
  name: string;
  boxCount: number;
  tier: 1 | 2;
  /** Narrative role of each box — the key to correct LLM template selection. */
  structure: string;
  tone: string[];
  bestFor: string;
  antiPatterns: string;
  /** Recommended max characters per box for this template's layout. */
  charLimit: number;
  examples: MemeExample[];
}

export interface MemeExample {
  boxes: string[];
  context: string;
}

// ─── Tier 1: Rich annotations (20 templates) ────────────────────────────────

const TIER_1: MemeTemplate[] = [
  {
    id: '181913649',
    name: 'Drake Hotline Bling',
    boxCount: 2,
    tier: 1,
    structure: 'Box 1: thing being rejected/ignored. Box 2: thing being chosen instead (usually worse or more absurd)',
    tone: ['dismissive', 'sarcastic', 'comparison'],
    bestFor: 'When someone ignores the obvious good choice for a worse one',
    antiPatterns: 'Not for simple facts or chronology (was/became). Both boxes need contrast/irony.',
    charLimit: 50,
    examples: [
      { boxes: ['Auditing smart contracts', 'Aping based on a CT thread'], context: 'project launches without audit' },
      { boxes: ['Taking profits at 10x', 'Diamond handing to -95%'], context: 'trader refuses to sell' },
      { boxes: ['Building actual product', 'Announcing strategic partnerships'], context: 'project all marketing no dev' },
    ],
  },
  {
    id: '112126428',
    name: 'Distracted Boyfriend',
    boxCount: 3,
    tier: 1,
    structure: 'Box 1 (boyfriend): who is distracted. Box 2 (other woman): shiny new thing. Box 3 (girlfriend): what they should be focused on',
    tone: ['betrayal', 'distraction', 'irony'],
    bestFor: 'When a project/person abandons something important for something flashy',
    antiPatterns: 'Needs three distinct elements. Not for simple two-way comparisons — use Drake.',
    charLimit: 35,
    examples: [
      { boxes: ['Crypto VCs', 'AI tokens', 'Their existing portfolio'], context: 'VCs chasing narratives' },
      { boxes: ['@SomeFounder', 'New chain launch', 'Fixing bugs on main product'], context: 'founder distracted by shiny object' },
      { boxes: ['Degen traders', 'Random new memecoin', 'The bag they just bought yesterday'], context: 'rotating bags instantly' },
    ],
  },
  {
    id: '55311130',
    name: 'This Is Fine',
    boxCount: 2,
    tier: 1,
    structure: 'Box 1: the disaster happening around them. Box 2: their absurdly calm statement or denial',
    tone: ['denial', 'copium', 'dark humor'],
    bestFor: 'Project/person pretending everything is ok while clearly failing',
    antiPatterns: 'Needs genuine disaster context. Not for mild inconveniences.',
    charLimit: 55,
    examples: [
      { boxes: ['TVL down 94%, devs leaving', 'We are building for the long term'], context: 'project in freefall' },
      { boxes: ['Token -80% this week', 'This is actually bullish'], context: 'copium posting' },
      { boxes: ['Chain halted 3 times', 'Our uptime is industry-leading'], context: 'L1/L2 reliability issues' },
    ],
  },
  {
    id: '129242436',
    name: 'Change My Mind',
    boxCount: 2,
    tier: 1,
    structure: 'Box 1: provocative opinion stated as fact on the sign. Box 2: usually empty or "Change My Mind"',
    tone: ['provocative', 'confident', 'challenge'],
    bestFor: 'Hot takes about crypto projects, bold claims that invite debate',
    antiPatterns: 'Only works with genuinely controversial statements. Not for obvious truths.',
    charLimit: 60,
    examples: [
      { boxes: ['Most L2s are just multisigs with extra steps', 'Change my mind'], context: 'L2 criticism' },
      { boxes: ['Your "decentralized" protocol has 3 admin keys', 'Change my mind'], context: 'decentralization theater' },
      { boxes: ['NFTs are just crypto beanie babies', 'Change my mind'], context: 'NFT market commentary' },
    ],
  },
  {
    id: '178591752',
    name: 'Tuxedo Winnie The Pooh',
    boxCount: 2,
    tier: 1,
    structure: 'Box 1: basic/normie version. Box 2: refined/sophisticated version of the same thing',
    tone: ['superiority', 'sophistication', 'ironic'],
    bestFor: 'Mocking how crypto rebrands basic things to sound fancy',
    antiPatterns: 'Both boxes must describe the SAME thing in different registers.',
    charLimit: 55,
    examples: [
      { boxes: ['Ponzi scheme', 'Sustainable yield farming'], context: 'DeFi yield criticism' },
      { boxes: ['We lost your money', 'Temporary negative equity rebalancing event'], context: 'exchange/protocol failure spin' },
      { boxes: ['Copy-pasting code', 'Forking and innovating'], context: 'projects forking without changes' },
    ],
  },
  {
    id: '226297822',
    name: 'Panik Kalm Panik',
    boxCount: 3,
    tier: 1,
    structure: 'Box 1 (panik): initial panic. Box 2 (kalm): brief relief. Box 3 (panik): worse realization',
    tone: ['escalation', 'false hope', 'anxiety'],
    bestFor: 'When a situation seems to improve then gets worse',
    antiPatterns: 'Needs three distinct emotional beats. Middle must be genuine (brief) relief.',
    charLimit: 45,
    examples: [
      { boxes: ['Token dumping', 'Team announces buyback', 'Buyback is from your own treasury'], context: 'fake buyback' },
      { boxes: ['Protocol hacked', 'White hat returns funds', 'They kept 10% as "bounty"'], context: 'hack aftermath' },
      { boxes: ['Dev wallet moves tokens', 'Just a routine transfer', 'To Binance deposit address'], context: 'dev dump suspicion' },
    ],
  },
  {
    id: '87743020',
    name: 'Two Buttons',
    boxCount: 3,
    tier: 1,
    structure: 'Box 1: option A (button). Box 2: option B (button). Box 3: who is sweating over the choice',
    tone: ['dilemma', 'indecision', 'impossible choice'],
    bestFor: 'When someone faces two equally bad or contradictory options',
    antiPatterns: 'Options must be genuinely conflicting. Not for easy choices.',
    charLimit: 40,
    examples: [
      { boxes: ['Admit the tokenomics are broken', 'Print more tokens', 'Every DeFi protocol'], context: 'tokenomics dilemma' },
      { boxes: ['Decentralize and lose control', 'Stay centralized and lose narrative', 'L1 founders'], context: 'decentralization vs control' },
      { boxes: ['Ship the product', 'Ship another blog post', 'VC-funded teams'], context: 'shipping vs marketing' },
    ],
  },
  {
    id: '252600902',
    name: 'Always Has Been',
    boxCount: 2,
    tier: 1,
    structure: 'Box 1: "Wait, it\'s all X?" Box 2: "Always has been" (with gun)',
    tone: ['revelation', 'cynical', 'conspiracy'],
    bestFor: 'Revealing that something was always a certain way, despite pretending otherwise',
    antiPatterns: 'Needs genuine "hidden truth" angle. Not for new developments.',
    charLimit: 45,
    examples: [
      { boxes: ['Wait, it\'s all just a multisig?', 'Always has been'], context: 'decentralization theater revealed' },
      { boxes: ['Wait, the yield comes from new deposits?', 'Always has been'], context: 'ponzi mechanics exposed' },
      { boxes: ['Wait, the "AI" is just an API wrapper?', 'Always has been'], context: 'AI project criticism' },
    ],
  },
  {
    id: '217743513',
    name: 'UNO Draw 25 Cards',
    boxCount: 2,
    tier: 1,
    structure: 'Box 1: the sensible/easy thing to do. Box 2: "or draw 25" — they\'d rather suffer than do the sensible thing',
    tone: ['stubbornness', 'self-destruction', 'absurd'],
    bestFor: 'When someone refuses to do the obvious right thing',
    antiPatterns: 'The sensible action must be genuinely easy. Draw 25 = exaggerated suffering.',
    charLimit: 45,
    examples: [
      { boxes: ['Take profits', 'or draw 25'], context: 'diamond hands gone wrong' },
      { boxes: ['Admit the roadmap is delayed', 'or draw 25'], context: 'project in denial about timeline' },
      { boxes: ['Stop launching tokens and build something', 'or draw 25'], context: 'serial token launchers' },
    ],
  },
  {
    id: '124822590',
    name: 'Left Exit 12 Off Ramp',
    boxCount: 3,
    tier: 1,
    structure: 'Box 1 (car): who is making the choice. Box 2 (straight road): the responsible/good path. Box 3 (exit ramp): the bad choice they\'re swerving toward',
    tone: ['bad decisions', 'swerving', 'irresponsible'],
    bestFor: 'When someone aggressively chooses the wrong path',
    antiPatterns: 'Needs clear "responsible vs irresponsible" contrast.',
    charLimit: 35,
    examples: [
      { boxes: ['@SomeProtocol', 'Fixing the exploit', 'Launching a governance token'], context: 'protocol priorities wrong' },
      { boxes: ['New crypto traders', 'Blue chip DeFi', '1000x dog tokens'], context: 'new trader behavior' },
      { boxes: ['VC-backed project', 'Product-market fit', 'Token launch at $1B FDV'], context: 'premature tokenization' },
    ],
  },
  {
    id: '188390779',
    name: 'Woman Yelling At Cat',
    boxCount: 2,
    tier: 1,
    structure: 'Box 1 (woman): angry/emotional accusation. Box 2 (cat): calm/unbothered response eating salad',
    tone: ['confrontation', 'unbothered', 'two perspectives'],
    bestFor: 'When two sides have completely different energy about the same situation',
    antiPatterns: 'Cat side must be genuinely calm/unbothered, not defensive.',
    charLimit: 50,
    examples: [
      { boxes: ['YOU SAID THIS WAS A SAFE INVESTMENT', 'ser i said "ape responsibly"'], context: 'rugpull aftermath' },
      { boxes: ['YOUR TOKEN IS DOWN 90%', 'we are in accumulation phase'], context: 'copium vs reality' },
      { boxes: ['YOU PROMISED MAINNET IN Q1', '*quietly moves roadmap to Q4*'], context: 'roadmap delays' },
    ],
  },
  {
    id: '97984',
    name: 'Disaster Girl',
    boxCount: 2,
    tier: 1,
    structure: 'Box 1: the destruction/chaos happening in background. Box 2: who is responsible and smugly watching',
    tone: ['arson', 'chaos', 'satisfied destruction'],
    bestFor: 'When someone/something causes destruction and seems pleased about it',
    antiPatterns: 'Needs a clear "perpetrator smiling at their own mess" dynamic.',
    charLimit: 50,
    examples: [
      { boxes: ['Entire DeFi ecosystem liquidating', '@SomeWhale after leveraged short'], context: 'whale manipulation' },
      { boxes: ['Community portfolio in ruins', 'The KOL who shilled it'], context: 'KOL damage' },
      { boxes: ['Token price cratering', 'Team that just unlocked vesting'], context: 'team dump' },
    ],
  },
  {
    id: '438680',
    name: 'Batman Slapping Robin',
    boxCount: 2,
    tier: 1,
    structure: 'Box 1 (Robin): naive/wrong statement being made. Box 2 (Batman): harsh correction via slap',
    tone: ['correction', 'harsh reality', 'shut down'],
    bestFor: 'Shutting down a naive or wrong crypto take',
    antiPatterns: 'Robin must say something genuinely naive, not just an opinion.',
    charLimit: 50,
    examples: [
      { boxes: ['But they said it\'s decentrali—', 'IT HAS 3 ADMIN KEYS'], context: 'decentralization theater' },
      { boxes: ['This time it\'s diffe—', 'IT\'S NEVER DIFFERENT'], context: 'cycle hopium' },
      { boxes: ['The team is doi—', 'THE TEAM IS DUMPING'], context: 'team dump reality' },
    ],
  },
  {
    id: '89370399',
    name: 'Roll Safe Think About It',
    boxCount: 2,
    tier: 1,
    structure: 'Box 1+2 combined: "Can\'t X if you Y" format — absurd logic that\'s technically true',
    tone: ['galaxy brain', 'absurd logic', 'technically correct'],
    bestFor: 'Absurd/galaxy-brain reasoning that exposes flawed logic',
    antiPatterns: 'Must follow "Can\'t X if Y" or "You don\'t need to X if Y" format.',
    charLimit: 55,
    examples: [
      { boxes: ['Can\'t get rugged', 'if you already lost everything in the last rug'], context: 'serial rugpull victim' },
      { boxes: ['Can\'t have a bank run', 'if you freeze withdrawals first'], context: 'exchange freezing withdrawals' },
      { boxes: ['Can\'t miss your roadmap deadlines', 'if you never set deadlines'], context: 'project with no roadmap' },
    ],
  },
  {
    id: '27813981',
    name: 'Hide the Pain Harold',
    boxCount: 2,
    tier: 1,
    structure: 'Box 1: what\'s actually happening (painful). Box 2: the forced smile/positive spin',
    tone: ['suffering', 'fake positivity', 'pain'],
    bestFor: 'When someone is clearly suffering but pretending everything is fine',
    antiPatterns: 'Must have genuine pain underneath the smile. Not for minor annoyances.',
    charLimit: 55,
    examples: [
      { boxes: ['Portfolio down 85%', '"I\'m in it for the tech"'], context: 'bagholder cope' },
      { boxes: ['Bought the top at $69k', '"I\'m a long-term investor now"'], context: 'top buyer rationalization' },
      { boxes: ['Team just dumped 40% of supply', '"They needed to fund development"'], context: 'community defending team dump' },
    ],
  },
  {
    id: '180190441',
    name: "They're The Same Picture",
    boxCount: 3,
    tier: 1,
    structure: 'Box 1: thing A. Box 2: thing B (supposedly different). Box 3: "They\'re the same picture" — pointing out they\'re identical',
    tone: ['exposure', 'comparison', 'indistinguishable'],
    bestFor: 'Pointing out two things are the same despite pretending to be different',
    antiPatterns: 'Things must be genuinely similar but presented as different.',
    charLimit: 40,
    examples: [
      { boxes: ['Ponzi scheme', 'Sustainable APY protocol', 'Corporate needs you to find the differences'], context: 'DeFi yield criticism' },
      { boxes: ['Centralized database', 'Enterprise blockchain', 'They\'re the same picture'], context: 'unnecessary blockchain' },
      { boxes: ['Exit scam', 'Strategic pivot and token migration', 'They\'re the same picture'], context: 'rebrand as exit' },
    ],
  },
  {
    id: '259237855',
    name: 'Laughing Leo',
    boxCount: 2,
    tier: 1,
    structure: 'Box 1: what is being watched/observed. Box 2: who is smugly laughing at it (implied: "I told you so")',
    tone: ['smugness', 'vindication', 'schadenfreude'],
    bestFor: 'Watching a predicted failure unfold',
    antiPatterns: 'Needs clear "I warned you" energy. Not for general amusement.',
    charLimit: 55,
    examples: [
      { boxes: ['Mfers who aped at ATH now posting "stay strong"', ''], context: 'watching top buyers cope' },
      { boxes: ['Project finally rugs after 50 red flags', 'Everyone who got called "FUD" for warning'], context: 'vindicated skeptics' },
      { boxes: ['"Crypto is dead" headlines for the 400th time', 'OGs who\'ve seen this exact cycle 4 times'], context: 'cycle veterans' },
    ],
  },
  {
    id: '100777631',
    name: 'Is This A Pigeon',
    boxCount: 3,
    tier: 1,
    structure: 'Box 1 (person): who is confused. Box 2 (butterfly): the thing being misidentified. Box 3: "Is this [wrong label]?"',
    tone: ['confusion', 'misidentification', 'cluelessness'],
    bestFor: 'When someone completely misidentifies or misunderstands something',
    antiPatterns: 'Needs genuine confusion/misidentification, not willful deception.',
    charLimit: 35,
    examples: [
      { boxes: ['New crypto projects', 'Centralized API', 'Is this Web3?'], context: 'fake decentralization' },
      { boxes: ['Crypto influencers', 'Paid promotion', 'Is this financial analysis?'], context: 'paid shills' },
      { boxes: ['VCs', 'Retail exit liquidity', 'Is this a community?'], context: 'VC dumping on retail' },
    ],
  },
  {
    id: '161865971',
    name: 'Marked Safe From',
    boxCount: 2,
    tier: 1,
    structure: 'Box 1: "marked safe from" — the thing survived. Box 2: context of what was avoided',
    tone: ['relief', 'survival', 'close call'],
    bestFor: 'Surviving a rug/hack/crash/drama',
    antiPatterns: 'Must reference a specific event or project.',
    charLimit: 55,
    examples: [
      { boxes: ['Marked safe from', 'today\'s memecoin rugpull'], context: 'daily rug commentary' },
      { boxes: ['Marked safe from', 'airdrop farming that protocol for 6 months'], context: 'failed airdrop expectations' },
      { boxes: ['Marked safe from', 'buying the KOL-shilled token at launch'], context: 'dodged a shill' },
    ],
  },
  {
    id: '222403160',
    name: 'Bernie I Am Once Again Asking',
    boxCount: 2,
    tier: 1,
    structure: 'Box 1: "I am once again asking" — who is asking. Box 2: what they\'re repeatedly asking for',
    tone: ['repetitive', 'begging', 'shameless'],
    bestFor: 'When someone keeps asking for the same thing repeatedly',
    antiPatterns: 'Must be something they ask repeatedly, not a one-time request.',
    charLimit: 55,
    examples: [
      { boxes: ['I am once again asking', 'for you to provide exit liquidity'], context: 'VC unlock approaching' },
      { boxes: ['I am once again asking', 'when mainnet'], context: 'delayed roadmap' },
      { boxes: ['I am once again asking', 'you to believe this dip is healthy'], context: 'serial copium posting' },
    ],
  },
];

// ─── Tier 2: Basic annotations (23 templates) ───────────────────────────────

const TIER_2: MemeTemplate[] = [
  {
    id: '135256802',
    name: 'Epic Handshake',
    boxCount: 3,
    tier: 2,
    structure: 'Box 1 (left arm): group A. Box 2 (right arm): group B. Box 3 (handshake): what they agree on',
    tone: ['agreement', 'unity', 'unlikely allies'],
    bestFor: 'Two opposing groups agreeing on something unexpected',
    antiPatterns: 'Groups must be genuinely different/opposing.',
    charLimit: 35,
    examples: [
      { boxes: ['Bitcoin maxis', 'ETH maxis', 'Hating Solana'], context: 'tribal unity' },
    ],
  },
  {
    id: '322841258',
    name: 'Anakin Padme 4 Panel',
    boxCount: 3,
    tier: 2,
    structure: 'Box 1 (Anakin): confident claim. Box 2 (Padme): "Right?" seeking confirmation. Box 3 (Anakin): silence/ominous stare',
    tone: ['ominous', 'bait and switch', 'dawning horror'],
    bestFor: 'When someone makes a claim and the truth is much darker',
    antiPatterns: 'Needs a genuine twist where the silence is terrifying.',
    charLimit: 45,
    examples: [
      { boxes: ['We\'re migrating to a new token', 'And I\'ll get the same value right?', '...'], context: 'token migration scam' },
    ],
  },
  {
    id: '309868304',
    name: 'Trade Offer',
    boxCount: 3,
    tier: 2,
    structure: 'Box 1: "I receive" (what they get). Box 2: "You receive" (what you get, usually much worse). Box 3: who is offering',
    tone: ['unfair deal', 'exploitation', 'audacity'],
    bestFor: 'Exposing unfair deals/tokenomics/terms',
    antiPatterns: 'Must have clear imbalance in the trade.',
    charLimit: 40,
    examples: [
      { boxes: ['I receive: your ETH', 'You receive: governance tokens with no value', 'DeFi protocols'], context: 'bad tokenomics' },
    ],
  },
  {
    id: '4087833',
    name: 'Waiting Skeleton',
    boxCount: 2,
    tier: 2,
    structure: 'Box 1: what they\'re waiting for. Box 2: skeleton (dead from waiting) or empty',
    tone: ['endless waiting', 'broken promises', 'death by delay'],
    bestFor: 'Waiting for something that will never come',
    antiPatterns: 'Must be genuinely long/hopeless wait.',
    charLimit: 55,
    examples: [
      { boxes: ['Me waiting for the mainnet launch they promised in 2024', ''], context: 'delayed roadmap' },
    ],
  },
  {
    id: '79132341',
    name: 'Bike Fall',
    boxCount: 3,
    tier: 2,
    structure: 'Box 1 (riding): action they took. Box 2 (stick in wheel): what they did to themselves. Box 3 (on ground): the result',
    tone: ['self-sabotage', 'self-inflicted', 'irony'],
    bestFor: 'When someone causes their own downfall',
    antiPatterns: 'Must be genuinely self-inflicted, not external.',
    charLimit: 35,
    examples: [
      { boxes: ['Crypto project doing well', 'Unnecessary token migration', 'Why did everyone leave?'], context: 'self-sabotage' },
    ],
  },
  {
    id: '284929871',
    name: 'They don\'t know',
    boxCount: 2,
    tier: 2,
    structure: 'Box 1: person in corner at party thinking. Box 2: what they know that others don\'t',
    tone: ['insider knowledge', 'lonely truth', 'knowing'],
    bestFor: 'When you know something the crowd doesn\'t realize yet',
    antiPatterns: 'Needs genuine hidden knowledge, not just an opinion.',
    charLimit: 55,
    examples: [
      { boxes: ['They don\'t know', 'the "community wallet" has a single signer'], context: 'hidden centralization' },
    ],
  },
  {
    id: '67452763',
    name: 'Squidward Window',
    boxCount: 2,
    tier: 2,
    structure: 'Box 1: Squidward watching enviously from inside. Box 2: what others are enjoying outside',
    tone: ['envy', 'FOMO', 'missing out'],
    bestFor: 'FOMO — watching others profit while you missed out',
    antiPatterns: 'Needs genuine missed opportunity.',
    charLimit: 50,
    examples: [
      { boxes: ['Me who sold at 2x', 'Holders who waited for 100x'], context: 'premature selling regret' },
    ],
  },
  {
    id: '99683372',
    name: 'Sleeping Shaq',
    boxCount: 2,
    tier: 2,
    structure: 'Box 1 (sleeping): thing they ignore. Box 2 (awake): thing they react to (usually trivial)',
    tone: ['selective outrage', 'misplaced priorities', 'hypocrisy'],
    bestFor: 'When someone ignores something important but reacts to something trivial',
    antiPatterns: 'Needs clear importance gap between the two things.',
    charLimit: 50,
    examples: [
      { boxes: ['$100M hack on their chain', 'Someone calling the logo ugly'], context: 'misplaced priorities' },
    ],
  },
  {
    id: '166969924',
    name: 'Flex Tape',
    boxCount: 3,
    tier: 2,
    structure: 'Box 1 (leak): the actual problem. Box 2 (tape): inadequate fix applied. Box 3: water still leaking despite tape',
    tone: ['band-aid fix', 'inadequate response', 'still broken'],
    bestFor: 'When a project applies a surface-level fix to a deep problem',
    antiPatterns: 'Fix must be obviously inadequate, not just imperfect.',
    charLimit: 35,
    examples: [
      { boxes: ['Protocol losing $1M/day to exploit', 'Pausing withdrawals', '*Exploit continues*'], context: 'ineffective security response' },
    ],
  },
  {
    id: '137501417',
    name: 'Friendship ended',
    boxCount: 2,
    tier: 2,
    structure: 'Box 1: "Friendship ended with X". Box 2: "Now Y is my best friend"',
    tone: ['loyalty switch', 'trend chasing', 'fickle'],
    bestFor: 'When someone/market rapidly switches allegiance',
    antiPatterns: 'Needs actual allegiance switch, not just preference.',
    charLimit: 45,
    examples: [
      { boxes: ['Friendship ended with Ethereum', 'Now Solana is my best friend'], context: 'chain loyalty switching' },
    ],
  },
  {
    id: '77045868',
    name: 'Pawn Stars Best I Can Do',
    boxCount: 2,
    tier: 2,
    structure: 'Box 1: what was expected/asked for. Box 2: "Best I can do is [much less]"',
    tone: ['lowball', 'disappointment', 'cheapness'],
    bestFor: 'When something delivers far less than promised',
    antiPatterns: 'Must have clear expectation vs reality gap.',
    charLimit: 55,
    examples: [
      { boxes: ['Community: we want token utility', 'Best I can do is a governance vote nobody reads'], context: 'empty governance' },
    ],
  },
  {
    id: '61520',
    name: 'Futurama Fry',
    boxCount: 2,
    tier: 2,
    structure: 'Box 1+2: "Not sure if X or Y" — squinting suspiciously at two possibilities',
    tone: ['suspicion', 'uncertainty', 'squinting'],
    bestFor: 'When you can\'t tell if something is genuine or deceptive',
    antiPatterns: 'Must follow "not sure if X or Y" format.',
    charLimit: 50,
    examples: [
      { boxes: ['Not sure if organic growth', 'or just wash trading'], context: 'suspicious volume' },
    ],
  },
  {
    id: '119139145',
    name: 'Blank Nut Button',
    boxCount: 2,
    tier: 2,
    structure: 'Box 1 (on button): what they\'re slamming. Box 2: who is slamming it',
    tone: ['urgency', 'impulse', 'can\'t resist'],
    bestFor: 'When someone can\'t resist doing something (usually bad)',
    antiPatterns: 'Must be an impulsive/irresistible action.',
    charLimit: 45,
    examples: [
      { boxes: ['APE INTO NEW TOKEN', 'Every degen at 3am'], context: 'impulsive trading' },
    ],
  },
  {
    id: '148909805',
    name: 'Monkey Puppet',
    boxCount: 2,
    tier: 2,
    structure: 'Box 1: the uncomfortable thing happening. Box 2: the awkward sideways glance (implied guilt or discomfort)',
    tone: ['awkward', 'guilty', 'nervous'],
    bestFor: 'When someone gets caught or something awkward surfaces',
    antiPatterns: 'Needs genuine awkwardness or guilt.',
    charLimit: 50,
    examples: [
      { boxes: ['Blockchain explorer showing team wallet selling', '@Founder posting "LFG" 5 min later'], context: 'caught selling while shilling' },
    ],
  },
  {
    id: '110163934',
    name: 'I Bet He\'s Thinking About Other Women',
    boxCount: 2,
    tier: 2,
    structure: 'Box 1 (woman thinking): assumption about what they\'re thinking. Box 2 (man thinking): what they\'re actually thinking about (crypto)',
    tone: ['obsession', 'distraction', 'relatable'],
    bestFor: 'Crypto obsession humor — thinking about charts/tokens instead of normal things',
    antiPatterns: 'Man\'s thought must be crypto-related and absurd.',
    charLimit: 55,
    examples: [
      { boxes: ['I bet he\'s thinking about other women', 'If I had bought SOL at $8 I\'d have...'], context: 'crypto what-if obsession' },
    ],
  },
  {
    id: '110133729',
    name: 'Spiderman Pointing At Spiderman',
    boxCount: 2,
    tier: 2,
    structure: 'Box 1: thing A pointing. Box 2: thing B pointing back. Both are identical/indistinguishable',
    tone: ['identical', 'accusation', 'mirror'],
    bestFor: 'Two projects/people accusing each other of the same thing they both do',
    antiPatterns: 'Both sides must be genuinely doing the same thing.',
    charLimit: 40,
    examples: [
      { boxes: ['Project A calling Project B centralized', 'Project B calling Project A centralized'], context: 'mutual hypocrisy' },
    ],
  },
  {
    id: '370867422',
    name: 'Megamind peeking',
    boxCount: 2,
    tier: 2,
    structure: 'Box 1: "No [X]?" — looking for something that doesn\'t exist. Box 2: empty or context',
    tone: ['emptiness', 'searching', 'lonely'],
    bestFor: 'When something expected is completely absent',
    antiPatterns: 'Must be something genuinely expected that\'s missing.',
    charLimit: 45,
    examples: [
      { boxes: ['No product?', ''], context: 'project with no actual product' },
    ],
  },
  {
    id: '50421420',
    name: 'Disappointed Black Guy',
    boxCount: 2,
    tier: 2,
    structure: 'Box 1 (happy): initial excitement. Box 2 (disappointed): the letdown',
    tone: ['letdown', 'disappointment', 'before/after'],
    bestFor: 'When something starts promising then disappoints',
    antiPatterns: 'Needs genuine excitement-to-disappointment arc.',
    charLimit: 50,
    examples: [
      { boxes: ['Project announces major update', 'It\'s just a UI redesign'], context: 'overhyped announcement' },
    ],
  },
  {
    id: '177682295',
    name: 'You Guys are Getting Paid',
    boxCount: 2,
    tier: 2,
    structure: 'Box 1: reveal that others got something. Box 2: "You guys are getting [X]?" — realizing they missed out',
    tone: ['FOMO', 'shock', 'left out'],
    bestFor: 'Realizing others got rewarded while you didn\'t',
    antiPatterns: 'Must be genuine surprise at missing out.',
    charLimit: 50,
    examples: [
      { boxes: ['Airdrop farmers getting $10k each', 'You guys are getting airdrops?'], context: 'missed airdrop' },
    ],
  },
  {
    id: '155067746',
    name: 'Surprised Pikachu',
    boxCount: 3,
    tier: 2,
    structure: 'Box 1: obvious thing that happened. Box 2: shocked face. Box 3: usually empty',
    tone: ['obvious outcome', 'fake surprise', 'predictable'],
    bestFor: 'When a completely predictable thing happens and people act shocked',
    antiPatterns: 'Must be genuinely predictable, not just unfortunate.',
    charLimit: 50,
    examples: [
      { boxes: ['Anonymous team rugs after raising $50M', '*surprised pikachu*', ''], context: 'predictable rug' },
    ],
  },
  {
    id: '309668311',
    name: 'Two Paths',
    boxCount: 3,
    tier: 2,
    structure: 'Box 1 (good path): sensible option. Box 2 (bad path): what they chose. Box 3: who is choosing',
    tone: ['bad decisions', 'wrong path', 'stubbornness'],
    bestFor: 'Choosing the obviously wrong option between two paths',
    antiPatterns: 'Similar to Left Exit — needs clear right/wrong paths.',
    charLimit: 35,
    examples: [
      { boxes: ['Sustainable tokenomics', '100% APY from inflation', 'New DeFi protocol'], context: 'bad tokenomics design' },
    ],
  },
  {
    id: '162372564',
    name: 'Domino Effect',
    boxCount: 2,
    tier: 2,
    structure: 'Box 1 (small domino): small initial event. Box 2 (large domino): massive consequence',
    tone: ['chain reaction', 'butterfly effect', 'escalation'],
    bestFor: 'When a small event causes massive consequences',
    antiPatterns: 'Must have plausible chain of causation.',
    charLimit: 45,
    examples: [
      { boxes: ['One dev pushes bad commit', 'Entire L2 halts for 7 hours'], context: 'cascading failure' },
    ],
  },
  {
    id: '61579',
    name: 'One Does Not Simply',
    boxCount: 2,
    tier: 2,
    structure: 'Box 1: "One does not simply". Box 2: the thing that\'s harder than people think',
    tone: ['warning', 'difficulty', 'underestimation'],
    bestFor: 'Warning about things people underestimate',
    antiPatterns: 'Slightly dated format — use sparingly.',
    charLimit: 50,
    examples: [
      { boxes: ['One does not simply', 'bridge to a new L2 without losing 3% to MEV'], context: 'bridging pain' },
    ],
  },
];

// ─── Exports ─────────────────────────────────────────────────────────────────

export const MEME_TEMPLATES: MemeTemplate[] = [...TIER_1, ...TIER_2];

export const TIER_1_IDS = new Set(TIER_1.map((t) => t.id));

export function getTemplateById(id: string): MemeTemplate | undefined {
  return MEME_TEMPLATES.find((t) => t.id === id);
}
